apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-rest-api-deployment
  labels:
    app: get-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-rest-api
  template:
    metadata:
      labels:
        app: get-rest-api
    spec:
      containers:
        - name: get-rest-api
          image: gchen63/get-rest-api:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: get-rest-api-service
spec:
  selector:
    app: get-rest-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
