name: Docker Image and Publish RC 2

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Login DockerHub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build -t rest-api .

    - name: Tag Docker image for the push
      run: docker tag rest-api:latest ${{ secrets.DOCKER_USER }}/rest-api
      
    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USER }}/rest-api
